### ISSUE TITLE
Add/Edit a member - implement all remaining fields (BE)

### ISSUE THREAD

**Issue by misayednap** [byoma-kusuma/bk-portal-api#17]
**Overview:** 
Implement the remaining fields on the Member Creation and Edit pages.  These fields are needed during registration.

**Current Status:**
Some of the fields have been implemented in the Create and Edit page.  

**Design Recommendation:**
IF THERE ARE ANY QUESTIONS, CONCERNS PLEASE REACH OUT TO @misayednap 

Add the following fields in the Member Table:

Membership Type (Life, Honorary etc) (membershipType)
Year of Birth (yearOfBirth)  - Nullable - Int

Phone (mobile) (phoneMobile)  - Nullable - String
Phone (land) (phoneLand)  - Nullable - String
Phone (other) (phoneOther)  - Nullable - String
currentAddressId - FK association to Address table
permanentAddressId - FK association to Address table
Note - Nullable - String

Add a new table called "Address" - add the following fields:

AddressId - Int
Street Address (permanentStreetAddress) - Nullable - String
City (permAddressCity) - Nullable - String
State/Province (permAddressState) - Nullable - String
Country - dropdown (code for now, lookup later) (permAddressCountry) - Nullable - String

 
REMOVE EXISTING FIELDS
   phonePrimary      String?
   phoneSecondary    String?
   centerAffiliation CentreAffiliationType
   permanentAddress  String?
   currentAddress    String?
   dob               DateTime?
   gender            GenderType?
 

**Acceptance Criteria:**

**Comment by xamogh** [comment]
@misayednap  i think you already did this?
